webtalk_init -webtalk_dir C:\\Users\\phil\\Documents\\vivado\\zybo_base_system\\source\\vivado\\hw\\zybo_bsd\\zybo_bsd.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mo Sep 29 01:10:47 2014" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210747612_0_0_303" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "upcdb904u86pedu1f9784d2gkl" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.2_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD FX(tm)-8320 Eight-Core Processor           " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3516 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1411938989828" -context "sdk\\\\application/1411938989828"
webtalk_add_data -client sdk -key hwid -value "1411765113016" -context "sdk\\\\application/1411938989828"
webtalk_add_data -client sdk -key bspid -value "1411765229506" -context "sdk\\\\application/1411938989828"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1411938989828"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1411938989828"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1411938989828"
webtalk_transmit -clientid 1644428870 -regid "210747612_0_0_303" -xml C:\\Users\\phil\\Documents\\vivado\\zybo_base_system\\source\\vivado\\hw\\zybo_bsd\\zybo_bsd.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\phil\\Documents\\vivado\\zybo_base_system\\source\\vivado\\hw\\zybo_bsd\\zybo_bsd.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\phil\\Documents\\vivado\\zybo_base_system\\source\\vivado\\hw\\zybo_bsd\\zybo_bsd.sdk\\webtalk\\sdk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
